baseURL = "http://stusta.zoidberg.stusta.de/"
canonifyURLs = true
defaultContentLanguage = "de"
title = "Studentenstadt Freimann"
enableRobotsTXT = true
disableHugoGeneratorInject = true
disableKinds = ["RSS"]
enableGitInfo = false


[Languages]
[Languages.en]
weight = 1
languageCode = "en-US"
languageName = "English"

[Languages.de]
weight = 2
languageCode = "de-DE"
languageName = "Deutsch"
