baseURL = "http://stusta.zoidberg.stusta.de/"
canonifyURLs = true
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Studentenstadt Freimann"
enableRobotsTXT = true
disableHugoGeneratorInject = true
disableKinds = ["RSS"]
enableGitInfo = false
